/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThinkingRouteImport } from './routes/thinking'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as ThinkingSlugRouteImport } from './routes/thinking.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingRoute = ThinkingRouteImport.update({
  id: '/thinking',
  path: '/thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingSlugRoute = ThinkingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThinkingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thinking': typeof ThinkingRouteWithChildren
  '/thoughts': typeof ThoughtsRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thinking': typeof ThinkingRouteWithChildren
  '/thoughts': typeof ThoughtsRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thinking': typeof ThinkingRouteWithChildren
  '/thoughts': typeof ThoughtsRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/thinking'
    | '/thoughts'
    | '/thinking/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/thinking'
    | '/thoughts'
    | '/thinking/$slug'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/thinking'
    | '/thoughts'
    | '/thinking/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThinkingRoute: typeof ThinkingRouteWithChildren
  ThoughtsRoute: typeof ThoughtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking': {
      id: '/thinking'
      path: '/thinking'
      fullPath: '/thinking'
      preLoaderRoute: typeof ThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/$slug': {
      id: '/thinking/$slug'
      path: '/$slug'
      fullPath: '/thinking/$slug'
      preLoaderRoute: typeof ThinkingSlugRouteImport
      parentRoute: typeof ThinkingRoute
    }
  }
}

interface ThinkingRouteChildren {
  ThinkingSlugRoute: typeof ThinkingSlugRoute
}

const ThinkingRouteChildren: ThinkingRouteChildren = {
  ThinkingSlugRoute: ThinkingSlugRoute,
}

const ThinkingRouteWithChildren = ThinkingRoute._addFileChildren(
  ThinkingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThinkingRoute: ThinkingRouteWithChildren,
  ThoughtsRoute: ThoughtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
